// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'ant-form-item-children': string;
  'ant-modal-title': string;
  'ant-tag': string;
  'card': string;
  'close': string;
  'comment': string;
  'content': string;
  'contentFile': string;
  'contentImg': string;
  'contentImgs': string;
  'contentLink': string;
  'contentText': string;
  'contentVideo': string;
  'contentWechat': string;
  'creat': string;
  'discuss': string;
  'download': string;
  'edit': string;
  'emoji': string;
  'fansTextContent': string;
  'footer': string;
  'ft60': string;
  'imgUrls': string;
  'main': string;
  'newsMain': string;
  'omit': string;
  'paging': string;
  'praise': string;
  'preview': string;
  'tags': string;
  'textContent': string;
  'texts': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
