// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-tooltip-arrow': string;
  'ant-tooltip-inner': string;
  'ft60': string;
  'storeNickNames': string;
}
declare var cssExports: CssExports;
export = cssExports;
