// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ft60': string;
  'm10': string;
  'weChatMag': string;
}
declare var cssExports: CssExports;
export = cssExports;
