// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ft60': string;
  'pageLoading': string;
  'spin': string;
}
declare var cssExports: CssExports;
export = cssExports;
