// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ft60': string;
  'handle': string;
  'sys': string;
  'user': string;
  'userName': string;
}
declare var cssExports: CssExports;
export = cssExports;
