// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-tag-checkable-checked': string;
  'checkTag': string;
  'ft60': string;
  'tagsMain': string;
  'tagsModal': string;
}
declare var cssExports: CssExports;
export = cssExports;
