// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-table': string;
  'ant-table-tbody': string;
  'friendMag': string;
  'ft60': string;
  'omit': string;
}
declare var cssExports: CssExports;
export = cssExports;
