// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ft60': string;
  'news': string;
  'newsMain': string;
  'paging': string;
}
declare var cssExports: CssExports;
export = cssExports;
