// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ft60': string;
  'img': string;
  'img-item': string;
}
declare var cssExports: CssExports;
export = cssExports;
