// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addition': string;
  'comment': string;
  'df': string;
  'editForm': string;
  'ellipsis': string;
  'fileBox': string;
  'fileContent': string;
  'ft60': string;
  'imgBox2': string;
  'like': string;
  'linkBox': string;
  'materialBox': string;
  'materialBox2': string;
  'mb10': string;
  'previewMass': string;
  'previewModal': string;
  'renderContent': string;
  'renderContentMain': string;
  'replyContent': string;
  'substance': string;
  'textBox': string;
}
declare var cssExports: CssExports;
export = cssExports;
