// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-col-8': string;
  'ant-form-item-children': string;
  'ant-form-item-control-wrapper': string;
  'ant-form-item-label-left': string;
  'autoAddUserChannel': string;
  'autoAddUserTimeLower': string;
  'col1': string;
  'ft60': string;
  'set': string;
}
declare var cssExports: CssExports;
export = cssExports;
