// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emoji': string;
  'emojiItem': string;
  'emojiModal': string;
  'ft60': string;
}
declare var cssExports: CssExports;
export = cssExports;
