// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collect': string;
  'dataStatement': string;
  'ft60': string;
  'table': string;
  'tableTitle': string;
}
declare var cssExports: CssExports;
export = cssExports;
