// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appWrapper': string;
  'ft60': string;
  'intlSelect': string;
}
declare var cssExports: CssExports;
export = cssExports;
