// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'components-form-demo-normal-login': string;
  'control': string;
  'ft60': string;
  'login': string;
  'login-form': string;
  'login-form-button': string;
  'login-form-forgot': string;
  'loginTip': string;
}
declare var cssExports: CssExports;
export = cssExports;
